apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-ocp-mcp
  labels:
    app: {{ include "mcp-server.name" . }}
    component: mcp
spec:
  replicas: {{ .Values.mcp.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mcp-server.name" . }}
      component: mcp
  template:
    metadata:
      labels:
        app: {{ include "mcp-server.name" . }}
        component: mcp
    spec:
      containers:
        - name: mcp-server
          image: "{{ .Values.mcp.image.repository }}:{{ .Values.mcp.image.tag }}"
          args:
            - '--port'
            - '{{ .Values.mcp.service.port }}'
          imagePullPolicy: {{ .Values.mcp.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mcp.service.port }}
          resources:
            {{- toYaml .Values.mcp.resources | nindent 12 }}
