{{- if .Values.mcp.rbac.serviceAccounts -}}
{{- $namespace := .Values.mcp.rbac.targetNamespace -}}
{{- range $sa := .Values.mcp.rbac.serviceAccounts }}
---
# RoleBinding for {{ $sa }} in namespace {{ $namespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $sa }}-admin-{{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ $sa | quote }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
