{{- if .Values.mcp.rbac.serviceAccounts -}}
{{- $namespace := .Values.mcp.rbac.targetNamespace -}}
{{- range $sa := .Values.mcp.rbac.serviceAccounts }}
---
# RoleBinding for {{ $sa }} in namespace {{ $namespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $sa }}-view-{{ $namespace }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mcp.name" . }}
    helm.sh/chart: {{ include "mcp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: {{ $sa | quote }}
  namespace: {{ $namespace }}
{{- end }}
{{- end }}
