apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.badimage.name }}
  labels:
    app: {{ .Values.badimage.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.badimage.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.badimage.name }}
    spec:
      containers:
      - name: {{ .Values.badimage.name }}
        image: "{{ .Values.badimage.image }}:{{ .Values.badimage.tag }}"
        imagePullPolicy: IfNotPresent
