apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.crashloop.name }}
  labels:
    app: {{ .Values.crashloop.name }}
spec:
  containers:
  - name: {{ .Values.crashloop.name }}
    image: "{{ .Values.crashloop.image }}:{{ .Values.crashloop.tag }}"
    command: {{ .Values.crashloop.command }}
    imagePullPolicy: IfNotPresent
  restartPolicy: {{ .Values.crashloop.restartPolicy }}
