apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-server.fullname" . }}-streamlit
  labels:
    app: {{ include "mcp-server.name" . }}
    component: streamlit
spec:
  replicas: {{ .Values.streamlit.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mcp-server.name" . }}
      component: streamlit
  template:
    metadata:
      labels:
        app: {{ include "mcp-server.name" . }}
        component: streamlit
    spec:
      containers:
        - name: streamlit
          image: "{{ .Values.streamlit.image.repository }}:{{ .Values.streamlit.image.tag }}"
      args:
        - '--sse-port'
        - '{{ .Values.streamlit.service.port }}'
          imagePullPolicy: {{ .Values.streamlit.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.streamlit.service.port }}
          resources:
            {{- toYaml .Values.streamlit.resources | nindent 12 }}
          env:
            - name: REMOTE_OCP_MCP_URL
              value: {{ .Values.remoteOcpMcpUrl | quote }}
            - name: TAVILY_SEARCH_API_KEY
              value: {{ .Values.tavilySearchApiKey | quote }}
            - name: REMOTE_BASE_URL
              value: {{ .Values.remoteBaseUrl | quote }}
            - name: INFERENCE_MODEL_ID
              value: {{ .Values.inferenceModelId | quote }}
