apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-server.fullname" . }}-streamlit
  labels:
    app: {{ include "mcp-server.name" . }}
    component: streamlit
spec:
  type: {{ .Values.streamlit.service.type }}
  ports:
    - port: {{ .Values.streamlit.service.port }}
      targetPort: {{ .Values.streamlit.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "mcp-server.name" . }}
    component: streamlit
